-- If this SQL looks weird, that's because it is.
-- These are data definitions generated by pg_dump on the original table created by the GDAL tools.
CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;

--
-- Name: EXTENSION postgis; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION postgis IS 'PostGIS geometry, geography, and raster spatial types and functions';

CREATE TABLE public.props (
    id integer NOT NULL,
    gisid character varying,
    town character varying,
    lat double precision,
    lon double precision,
    prop_addr character varying,
    unit character varying,
    own character varying,
    co character varying,
    own_addr character varying,
    ass_val double precision,
    year character varying,
    sale_d timestamp with time zone,
    sale_p double precision,
    owners character varying,
    clst integer,
    conf double precision,
    count integer,
    wkb_geometry public.geometry(Geometry,4326)
);

CREATE SEQUENCE public.props_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER TABLE public.props_id_seq OWNER TO postgres;

ALTER SEQUENCE public.props_id_seq OWNED BY public.props.id;

ALTER TABLE ONLY public.props ALTER COLUMN id SET DEFAULT nextval('public.props_id_seq'::regclass);

ALTER TABLE ONLY public.props
    ADD CONSTRAINT props_pkey PRIMARY KEY (id);


CREATE INDEX props_wkb_geometry_geom_idx ON public.props USING gist (wkb_geometry);